version: '3.8'

services:
  scraper:
    user: root
    build: .
    volumes:
      - ./archive:/root/archive
    environment:
      - DISPLAY=:99
    command: ["sh", "-c", "cron && Xvfb :99 -ac & tail -f /var/log/cron.log"]
