version: '3.8'

services:
  x_scraper:
    user: root
    build: ./X
    volumes:
      - ./archive:/root/archive
    environment:
      - DISPLAY=:99
    command: ["sh", "-c", "cron && Xvfb :99 -ac & tail -f /var/log/cron.log"]
    depends_on:
      - mongo


  # Service for Instagram scraper
  insta_scraper:
    user: root
    build: ./Instagram  # Adjust the path as needed for the Instagram scraper
    environment:
      - DISPLAY=:99
    command: ["sh", "-c", "cron && Xvfb :99 -ac & tail -f /var/log/cron.log"]
    depends_on:
      - mongo


  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db  # To persist data on host
    ports:
      - "27017:27017"  # Expose MongoDB port

volumes:
  mongo_data: